name: Publish Package to GitHub NPM Registry

on: 
  ????: 
    
jobs:
    npm-package:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
