name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
    
jobs:
    unit-testing:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
      steps:
        - uses: actions/checkout@v4
        # Setup .npmrc file to publish to GitHub Packages
        - uses: actions/setup-node@v4
          with:
            node-version: '20.x'
            # registry-url: 'https://npm.pkg.github.com/'
            # # Defaults to the user or organization that owns the workflow file
            # scope: '@cd-org'
        # - run: |
        #       ls -ltra
        #       cat $NPM_CONFIG_USERCONFIG
        - run: npm ci
        - run: |
            # echo '@cd-org:registry=https://npm.pkg.github.com/' > ${{ github.workspace }}/.npmrc
            cat .npmrc
            npm publish
          env:
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
