name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
    
jobs:
    unit-testing:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      steps:
        - uses: actions/checkout@v4
        # Setup .npmrc file to publish to GitHub Packages
        - uses: actions/setup-node@v4
          with:
            node-version: '20.x'
            registry-url: 'https://npm.pkg.github.com/'
            scope: '@cd-org'
        - run: |
              ls -ltra
              # echo '//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}' > ${{ github.workspace }}/.npmrc
              # cat .npmrc
              cat /home/runner/work/_temp/.npmrc
        - run: npm ci
        - run: |
            cp /home/runner/work/_temp/.npmrc ${{ github.workspace }}/.npmrc
            npm publish
          env:
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
